# Generated by Django 5.2.4 on 2025-07-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faculty_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='email',
        ),
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
