# Generated by Django 5.2.4 on 2025-07-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_faculty_availability_remove_faculty_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='availability',
            field=models.TextField(blank=True, null=True),
        ),
    ]
