# Generated by Django 5.2.4 on 2025-10-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='exam_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.examsession'),
        ),
    ]
